development:
  adapter: postgresql
  database: MAXdevelopment
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

test:
  adapter: postgresql
  database: MAXtest
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

production:
  adapter: postgresql
  database: db
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

